name: beezar_v2
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  get: ^4.6.6
  get_storage: ^2.1.1
  flutter_svg: ^2.0.7
  flutter_otp_text_field: ^1.1.1
  dots_indicator: ^3.0.0
  url_launcher: ^6.1.14
  dropdown_search: ^5.0.6
  cached_network_image: ^3.3.0
  gradient_borders: ^1.0.0
  font_awesome_flutter: ^10.5.0
  mailer: ^6.0.1
  image_picker: ^1.0.4
  google_sign_in: ^6.1.5
  flutter_login_facebook: ^1.8.0
  path_provider: ^2.1.1

  flutter_localizations:
    sdk: flutter 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
  fonts:
    - family: Cairo
      fonts:
        - asset: lib/assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Cairo-Black.ttf          
        - asset: lib/assets/fonts/Cairo-ExtraBold.ttf
          weight: 900
        - asset: lib/assets/fonts/Cairo-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Cairo-SemiBold.ttf
          weight: 600